language: go
go:
- 1.7
- 1.8
- tip

install:
- go get -u github.com/Masterminds/glide
- go get -u github.com/mattn/goveralls
- glide install

before_script:
- go vet $(glide nv)

script:
- goveralls -repotoken $COVERALLS_TOKEN

cache:
  directories:
  - vendor

before_deploy:
- make zip

deploy:
  provider: releases
  file:
  - geoffrey-${TRAVIS_TAG}-linux32.zip
  - geoffrey-${TRAVIS_TAG}-linux64.zip
  - geoffrey-${TRAVIS_TAG}-win64.zip
  - geoffrey-${TRAVIS_TAG}-win32.zip
  - geoffrey-${TRAVIS_TAG}-darwin.zip
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_GO_VERSION == "1.8"
  api_key:
    secure: t7/mUrgN6ec3ox2Jd2TvrnBme/8d74PIVNOmp/AB+oqrXD0HKa/iF0DI7aXQC440C43lpzLIv65Wb6SPpNezy2V/MbMEsWXpwiSl+CTcoFP6Fg/WK0+tKkuNZT7CfQ0KU1PBx5RSHTp6H0ZUi/1WIgMYrEU+RppdnSXq2fvoM25JIxn3Go36xMsVsAMnSIY1+Z9Uppj+8b4D93UneSGaCUSDnAny1gaHYhqucjMuedQKTeOFpu3ux2oc4/09ubFHi6VPdOCLHebbUcSUfC+EWf3D6znxOBmzqaV/yz+7FqjBsAPpE+WbO0mGyaI6u+rE5AUzkh+pgHC4KH02UdC7OMtOVN36axnzGTuLyEdB0vcS7zOHWGMNkNT9jjxfYMDJimsgPidPU57/1Dr7FoPDxdPcUQqydpY1+8FMLh3eVU/prU2kheGK/kD/Yc37nVTLi+nbD0g/lkcCTImzZAFbHFQtJdvdXD92UdFW/Gy2jKAOxJb3S2JTlE9P+kzK/9g0QO0X6r3veZQP3yWPxO27VbmlaPWSzSnoWSmzgsDJtvjFC6QcfVdpp12uR2LcdIb4lWzymK1TyIO0ktHzzhVfHmFFE24KDpWX3uWKJcpGPX2ZJQ+NO5nZ/a8VlV0NHuvPn6+utjjmXvfJmbEiuuK4b9PEpl5Vkz126x4QEzai5HM=

notifications:
  pushover:
    users:
      secure: fEfLhcwC7GFwcFsc0egfzveZOxD2V0ZA7OTlULY8H9b7lXZRRQId9rVQ3XJfGLndhxX+skpru1usoWthwJJ78ajQnFPg3rV6CHGYtQ9O+HaZIIlGUesgaeUIUurTJ5Z3k52DJ+KeC3/tcZpVy3mKre+2QgQrNIqCcoUhYFgkriz+L561805Bh71CMtwyLnCrKLMhTgf/gZSL3mZqaOY+JjO4iT+THIdN41IeFO82CyEjDZK0IRZ1AuWpB0NpG6CLCPrtoYUviAJSZYslPHUYa01osldlbKmAXrqGqRlpXbulz6Z4h3AXKTsz5+0fPLqT3f5wC/o6uoLdFJH+ZVPhSEZQlAAZrr5IhqTczsdcKwOAPDGUU4LAfb+awNuMjIKICV5ajbwLVEtT7dMKWi4Rz0LBCtRGwBtVQxqdhojbvMTVe+rBYCU7DXg/w9hj8fQbLMO42z4bRf14Hv7oiGW159228mStj4NfdjGEc7sgOKHa0FY4nRwi3lgQp3tpDx5w9OegvmqfqqIbV/Pn7QbafeT9tEoTcLyobLkLei6/cytXNGh6tttumYik9/aajkL9jj19oPdKyxxYHbQyLMLcOfj0yqZNvcjxZNb+uKlqblDaIcVaZcP7xOLFtDg+HXLBt1huD/sNyj9/L9UoKruvvyhAwRdrBHWwKt47m2vVJsI=
    api_key:
      secure: JfU3gMo+PXkqyfCi/dX19gFIMduUhgF9vo4AujVBI41hhxcyWV9tstoj0In0YRPg8F0AMhHjSwucJzbn3vtZ5MRimKHMWWa/8ptX2zMcxbxwXaU+ZLk/qmC318KJXrfWq5z07AOtd9QuepH/m1zmu93pdKFHKSgTTh6M/8ldInTU/+dRXhnHEF/xqtl9T96jDZnTRboKPhW2E1IkGDdeJ+bC7Cy/+C/SP2+j7B1FNi6FliG0WBNkj3mJoRTX1Ak+fOwcDeuC6VGCFqvWAXPjzeM8tqHO/QjxYoYU+Z6/v5TAZZ6r/tNqgmdXIt91/vv6RUACwKO5QZnqpCg5oVcA84f6h9QbjerUXvq2Ekm7dllhCu3WF8Pfy1Zo4L2BcdlnHZHhYG5z5lzD95JgfePggzMhyg4pcfWR1e5Zlv+ZY//heLNcXbraJ5h9ijwiw/LatER8CWUs343VnMepHbWSOHh4Z4x6YISkrGmi0kHLUhcP5scqW6LmsIbAv20Yst3oe6dXwMNBguIj+VNYiH3lZg39u/CElHDhHX/9X2dRzIaRgwyKZGZogVymDwaNhed8FgV5ZVUotJDPeB+UlBtyYyaGuiAxTOsgYFEeau9T8zmUWsVogIhJhId65ueLgjqPfPgQfoB4mf4Kobb5Up9JYQTlZzpJTVyCb0f8n5mzJ3o=

env:
  global:
    secure: r+ftY28BB5j2ThVlZtO14p09VtQUXoSBpR33woh8h8KaVSwmybU/MeFNmT7y+diX5NJZp63Cbm5gC8YarrtGzRQNECk4XrkFAeh/sQ3CL8ffJD9n1j+Jn+ZVs3zyeTX2Da8JCDszBSIzBbj7+i6VpaJ2B1D92tjVhEWhcKCn262LtrngeWfafG/B3g+7UB3CBbNWEos23gZsjBGaRkTNseXxD2zidgwaeSvEHMs38x4bD7S43uy6PbNiegsRMDCf2vQuzoDoAWXPJ0Qm3VivLvPkGki0Uz1p/E5VqdRbFcbub1G+HYIQEGxNbOAyKdTP6DSsgpNhln7nEQknacFkKmBZ5X62An5IR/aNCHcPZ4VxNZl2BrHbjDUCny275uNq3CvNXE5vpjFlX2+bIVUdw/Pvd1OvneXDF4DYWXXnNq8HmWdRmiLY+dumIFZ6cyI4OUAqQtLiHg3cp+DU68xahVSb354Unj+FrRmAIGECJoAI5fI0i4RtSpGg7VMWi/Lu6LdXJMU5RZS0WPzHrva8hnbvqeHOAsLKwf+69+DEPFXGN5ygLl7PAEk0FjIEZj8CDIvMQmj+dw1KgRVleJHXx3VZPZ71PbTGqoIkBBs4UG6Prweoo0iTzPjkjt0iBY5+BOJMAHsUPzwVBmWmNaQbukUcSU47gvlWJ/n1UjhHDS0=
