language: go
go:
    - 1.6
    - 1.7
    - tip

install:
    - go get -v github.com/Masterminds/glide
    - glide install

before_script:
    - go vet $(glide nv)

script:
    - go test $(glide nv)

cache:
    directories:
        - vendor