language: go
go:
  - 1.6
  - 1.7
  - tip

install:
  - go get -v github.com/Masterminds/glide
  - glide install

before_script:
  - go vet $(glide nv)

script:
  - go test $(glide nv)

cache:
  directories:
  - vendor

notifications:
  pushover:
    users:
      secure: fEfLhcwC7GFwcFsc0egfzveZOxD2V0ZA7OTlULY8H9b7lXZRRQId9rVQ3XJfGLndhxX+skpru1usoWthwJJ78ajQnFPg3rV6CHGYtQ9O+HaZIIlGUesgaeUIUurTJ5Z3k52DJ+KeC3/tcZpVy3mKre+2QgQrNIqCcoUhYFgkriz+L561805Bh71CMtwyLnCrKLMhTgf/gZSL3mZqaOY+JjO4iT+THIdN41IeFO82CyEjDZK0IRZ1AuWpB0NpG6CLCPrtoYUviAJSZYslPHUYa01osldlbKmAXrqGqRlpXbulz6Z4h3AXKTsz5+0fPLqT3f5wC/o6uoLdFJH+ZVPhSEZQlAAZrr5IhqTczsdcKwOAPDGUU4LAfb+awNuMjIKICV5ajbwLVEtT7dMKWi4Rz0LBCtRGwBtVQxqdhojbvMTVe+rBYCU7DXg/w9hj8fQbLMO42z4bRf14Hv7oiGW159228mStj4NfdjGEc7sgOKHa0FY4nRwi3lgQp3tpDx5w9OegvmqfqqIbV/Pn7QbafeT9tEoTcLyobLkLei6/cytXNGh6tttumYik9/aajkL9jj19oPdKyxxYHbQyLMLcOfj0yqZNvcjxZNb+uKlqblDaIcVaZcP7xOLFtDg+HXLBt1huD/sNyj9/L9UoKruvvyhAwRdrBHWwKt47m2vVJsI=
    api_key:
      secure: JfU3gMo+PXkqyfCi/dX19gFIMduUhgF9vo4AujVBI41hhxcyWV9tstoj0In0YRPg8F0AMhHjSwucJzbn3vtZ5MRimKHMWWa/8ptX2zMcxbxwXaU+ZLk/qmC318KJXrfWq5z07AOtd9QuepH/m1zmu93pdKFHKSgTTh6M/8ldInTU/+dRXhnHEF/xqtl9T96jDZnTRboKPhW2E1IkGDdeJ+bC7Cy/+C/SP2+j7B1FNi6FliG0WBNkj3mJoRTX1Ak+fOwcDeuC6VGCFqvWAXPjzeM8tqHO/QjxYoYU+Z6/v5TAZZ6r/tNqgmdXIt91/vv6RUACwKO5QZnqpCg5oVcA84f6h9QbjerUXvq2Ekm7dllhCu3WF8Pfy1Zo4L2BcdlnHZHhYG5z5lzD95JgfePggzMhyg4pcfWR1e5Zlv+ZY//heLNcXbraJ5h9ijwiw/LatER8CWUs343VnMepHbWSOHh4Z4x6YISkrGmi0kHLUhcP5scqW6LmsIbAv20Yst3oe6dXwMNBguIj+VNYiH3lZg39u/CElHDhHX/9X2dRzIaRgwyKZGZogVymDwaNhed8FgV5ZVUotJDPeB+UlBtyYyaGuiAxTOsgYFEeau9T8zmUWsVogIhJhId65ueLgjqPfPgQfoB4mf4Kobb5Up9JYQTlZzpJTVyCb0f8n5mzJ3o=
